name: fdsafaa
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: fdsafaa
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-03-14 18:34:11'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-03-14 18:34:11'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-03-14 18:34:11'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlOrchestratorPipelines: {}
sqlBusinessApps: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-03-14T18:34:11.586261Z'
  name: plibMaven
  version: 8.10.0-SNAPSHOT
  id: '687444525'
  createdAt: '2025-03-14T18:34:11.586261Z'
  type: plibMaven
- modifiedAt: '2025-03-14T18:34:11.586261Z'
  name: plibPypi
  version: 1.9.38
  id: '872481401'
  createdAt: '2025-03-14T18:34:11.586261Z'
  type: plibPypi
projectDependencies:
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/5Hm0Dy3f_team_4/5Hm0Dy3f_project_5.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-03-14 18:33:50'
  '120':
    projectUID: 120
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/5Hm0Dy3f_team_4/sVe2Q6TF_project_120.git&subPath=
    version: 0.2.40
    isDefault: true
    author: null
    createdAt: '2025-03-14 18:33:50'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
