name: protectedMainBranch
description: ''
version: 0.0.1
author: kiranadmin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: protectedmainbranch
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-12-22 06:02:04'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiranadmin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-22 06:02:04'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-12-22 06:02:04'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.7
    isDefault: true
    author: null
    createdAt: '2023-12-22 06:01:49'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-12-22 06:01:49'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
